### ISSUE TITLE
Transfer into asdf-community?

### ISSUE THREAD

**Issue by adamchainz** [asdf-community/asdf-python#116]
I use pyenv, but I've heard about asdf, and was researching to see if it was worth changing. I had heard asdf supported Python, but when I followed the latest documentation, this was pretty hard to discover.

The `asdf plugin add` [docs](https://asdf-vm.com/manage/plugins.html#add) encourages using GitHub repo URL’s over short names. So I understood I wanted to find the Python GitHub repo.

The "Plugins" menu on the site lists first party plugins, then community plugins in the `asdf-community` organization, then "GitHub Topics Search" and "Plugin shortname index". The last two options don't seem well supported to me as a new user, so after checking `asdf-community` it felt like using asdf for python isn't really supported... Only after further searching did I find this plugin.

I think you could really help discoverability by transferring to asdf-community - I spotted the docs here: https://github.com/asdf-community/.github#how-do-i-move-plugins-here

**Comment by diek** [comment]
Hey Adam, I recently have decided to give asdf a go to manage Python installs. I concur, and I hope someone takes action so this project can get some wider support and love from the Python community

**Comment by boldandbrad** [comment]
I agree with OP. I currently use pyenv but I regularly use other programming languages as well and wanted to give asdf a try. This repo was very hard to find. Please consider moving it to asdf-community for better visibility and support. Thanks :)

**Comment by matan129** [comment]
Any thoughts? @danhper

**Comment by danhper** [comment]
Thanks for the comments.
Definitely happy to do that!
I'll check out what the steps to do that are.
