### ISSUE TITLE
error install python 3.11.3 in ubuntu

### ISSUE THREAD

**Issue by 2004Lucas** [asdf-community/asdf-python#156]
lucaslinux@lucaspc:~/Downloads$ asdf install python 3.11.3
python-build 3.11.3 /home/lucaslinux/.asdf/installs/python/3.11.3
Downloading Python-3.11.3.tar.xz...
-> https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tar.xz
Installing Python-3.11.3...

BUILD FAILED (Ubuntu 22.04 using python-build 2.3.17-4-gb3c91b37)

Inspect or clean up the working tree at /tmp/python-build.20230412142040.39955
Results logged to /tmp/python-build.20230412142040.39955.log

Last 10 log lines:
  File "/tmp/python-build.20230412142040.39955/Python-3.11.3/Lib/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230412142040.39955/Python-3.11.3/Lib/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230412142040.39955/Python-3.11.3/Lib/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20230412142040.39955/Python-3.11.3/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpktksw3_6/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmpktksw3_6/pip-22.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpktksw3_6\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1860: install] Error 1
lucaslinux@lucaspc:~/Downloads$

**Comment by jdxcode** [comment]
you will need to open the log file to see more details, but see python-build's wiki on build issues: https://github.com/pyenv/pyenv/wiki/Common-build-problems
