### ISSUE TITLE
Support `.python-version` if `legacy_version_file = yes`

### ISSUE THREAD

**Issue by jasopolis** [asdf-community/asdf-python#158]
This plugin does not currently support reading the version file from `pyenv` -- to bring it in line with the Ruby and Node plugins, we should support `.python-version`, as described in the Getting Started guide (https://asdf-vm.com/guide/getting-started.html#using-existing-tool-version-files).

Happy to try put up a PR if they're being accepted!

**Comment by jasopolis** [comment]
Apologies, this actually is supported already!

**Comment by alexey-asl** [comment]
> Apologies, this actually is supported already!

hi, that does not seem to be supported in > 0.16 versions, right? 
https://asdf-vm.com/manage/configuration.html#legacy-version-file

**Comment by jasopolis** [comment]
It works for me, and I can see it in the source at https://github.com/asdf-community/asdf-python/blob/master/bin/list-legacy-filenames

**Comment by alexey-asl** [comment]
indeed, just gave it another try. Perhaps, last time I was expecting to work with both `.tool-versions` and `.python-version` with first taking precedence over other(if both present). But I see now that its either, either.

**Comment by rnestler** [comment]
Something seems to be very odd at least when using `asdf` 0.16 and a `.python-version` file:

```
$ cat .python-version
3.13.2
$ asdf install
version 3.13.2 of python is already installed
$ asdf list python
 *3.13.2
$ asdf which python
unexpected error: no versions set for python
$ python --version
No version is set for command python
```

So `install` and `list` seem to work, but actually using the version fails.

**Comment by alexey-asl** [comment]
> Something seems to be very odd at least when using `asdf` 0.16 and a `.python-version` file:
> 
> ```
> $ cat .python-version
> 3.13.2
> $ asdf install
> version 3.13.2 of python is already installed
> $ asdf list python
>  *3.13.2
> $ asdf which python
> unexpected error: no versions set for python
> $ python --version
> No version is set for command python
> ```
> 
> So `install` and `list` seem to work, but actually using the version fails.

it could be due to malformed python installation.
I experienced similar situations when specific python version was installed improperly. 
Usually the `uninstall` and `install` helped.

**Comment by rnestler** [comment]
> it could be due to malformed python installation.

Indeed. The "installation" was just an empty folder. Removing it fixed it.
